---
- name: "Step 1: checks"
  ansible.builtin.include_tasks: checks.yaml

- name: "Step 2: install packages"
  tags: migration
  ansible.builtin.include_tasks: packages.yaml

- name: "Step 3: installing nginx on the new server"
  when: inventory_hostname == 'newServer'
  ansible.builtin.include_tasks: newServer/nginx.yaml

- name: "Step 4: installing certbot on the new server and issuing certificates"
  when: inventory_hostname == 'newServer'
  ansible.builtin.include_tasks: newServer/certbot.yaml

- name: "Step 5: installing gitlab on the new server"
  tags: migration
  when: inventory_hostname == 'newServer'
  ansible.builtin.include_tasks: newServer/installGitlab.yaml

- name: "Step 6: create configuration backup on the old server"
  tags: migration
  when: inventory_hostname == 'oldServer'
  ansible.builtin.include_tasks: oldServer/configurationBackup.yaml

- name: "Step 7: restore configuration backup on the new server"
  tags: migration
  when: inventory_hostname == 'newServer'
  ansible.builtin.include_tasks: newServer/configurationBackup.yaml

- name: "Step 8: create backup on the old server"
  tags: migration
  when: inventory_hostname == 'oldServer'
  ansible.builtin.include_tasks: oldServer/backup.yaml

- name: "Step 9: restore backup on the new server"
  tags: migration
  when: inventory_hostname == 'newServer'
  ansible.builtin.include_tasks: newServer/restoreBackup.yaml

- name: "Step 10: restore the old server"
  tags: migration
  when: inventory_hostname == 'oldServer'
  ansible.builtin.include_tasks: oldServer/restore.yaml

- name: "Step 11: update domain"
  tags: domain
  when: inventory_hostname == 'newServer'
  ansible.builtin.include_tasks: newServer/updateDomain.yaml
