---

- name: Remove "certbot" package from apt
  ansible.builtin.apt:
    name: certbot
    state: absent

- name: Install "certbot" via snap
  community.general.snap:
    name: certbot
    classic: true

- name: Create a symbolic link
  ansible.builtin.file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link

- name: Generate certificates
  ansible.builtin.include_tasks: common/generateCertificates.yaml
