---

- name: Update repositories cache and install "nginx" package
  ansible.builtin.apt:
    name: nginx
    update_cache: true
    state: present

- name: Start nginx
  ansible.builtin.systemd_service:
    state: started
    name: nginx
    enabled: true

- name: Ufw allow 'Nginx Full'
  community.general.ufw:
    rule: allow
    name: 'Nginx Full'

- name: Collect configs in /etc/nginx/conf.d
  ansible.builtin.find:
    paths: /etc/nginx/conf.d/
    hidden: true
    recurse: true
    file_type: any
  register: collected_files

- name: Remove collected configs
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ collected_files.files }}"

- name: Configure gitlab nginx
  ansible.builtin.template:
    src: "gitlabNginx.j2"
    dest: "/etc/nginx/conf.d/{{ gitlab_domain }}.conf"
    mode: "0644"

- name: Configure registry nginx
  ansible.builtin.template:
    src: "registryNginx.j2"
    dest: "/etc/nginx/conf.d/registry.{{ gitlab_domain }}.conf"
    mode: "0644"

- name: Check nginx config
  ansible.builtin.command: nginx -t
  register: result
  failed_when: result.rc != 0
  changed_when: true
  notify: Restart nginx
