---

- name: Unblock new CI/CD jobs
  ansible.builtin.include_tasks: common/unBlockCICD.yaml

- name: Enable GitLab services
  ansible.builtin.blockinfile:
    path: "/etc/gitlab/gitlab.rb"
    state: absent
    block: |
      alertmanager['enable'] = false
      gitlab_exporter['enable'] = false
      gitlab_pages['enable'] = false
      gitlab_workhorse['enable'] = false
      grafana['enable'] = false
      logrotate['enable'] = false
      gitlab_rails['incoming_email_enabled'] = false
      nginx['enable'] = false
      node_exporter['enable'] = false
      postgres_exporter['enable'] = false
      postgresql['enable'] = false
      prometheus['enable'] = false
      puma['enable'] = false
      redis['enable'] = false
      redis_exporter['enable'] = false
      registry['enable'] = false
      sidekiq['enable'] = false

- name: Gitlab reconfigure
  ansible.builtin.include_tasks: common/gitlabReconfigure.yaml

- name: Show GitLab status
  ansible.builtin.include_tasks: common/showGitlabStatus.yaml
  